_target_: lightning.Trainer

default_root_dir: ${paths.output_dir}

# checkpoint_callback:
#     - best_model_path: model_storage/epoch0-checkpoint.ckpt

min_epochs: 1 # prevents early stopping
max_epochs: 3
# limit_train_batches: 
# limit_val_batches: 0.9
# limit_test_batches: 0.9

accelerator: gpu
devices: auto
log_every_n_steps: 10

# mixed precision for extra speed-up
# precision: 16

# perform a validation loop every N training epochs
check_val_every_n_epoch: 1

# set True to to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: False