_target_: src.models.cat_dog_classifier.CatDogClassifier

# Model parameters
base_model: test_vit.r160_in1k
num_classes: 2
pretrained: False
depths: (1, 1, 2, 1)
dims: (4, 8, 8, 16)
patch_size: 8

# Optimizer parameters
lr: 1e-3
weight_decay: 1e-5

# Scheduler parameters
factor: 0.1
patience: 10
min_lr: 1e-6